repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
  - id: black
    args: [--line-length=100]
- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    args: [--max-line-length=100]
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.8.0
  hooks:
  - id: nbqa-black
    args: [--line-length=100]
  - id: nbqa-flake8
    args: [--max-line-length=100]
